use_frameworks!

platform :ios, '10.0'

target 'kbeaconlib_Example' do
   pod 'kbeaconlib', :path => '../'
   pod 'iOSDFULibrary'
   pod 'AFNetworking/NSURLSession', '3.2.1'
   pod 'AFNetworking/Reachability', '3.2.1'
   pod 'AFNetworking/Security', '3.2.1'
   pod 'AFNetworking/Serialization', '3.2.1'
   pod 'MJRefresh'
end
